#!/bin/bash
#
# Install Leap Monitor as a desktop app on Linux.
# Creates a launcher script, icon, and .desktop entry so the monitor
# appears in GNOME / KDE / etc. app launchers.
#
# Usage: install-monitor-linux.sh <repo-path>
#
set -e

REPO_PATH="${1:-$(git rev-parse --show-toplevel 2>/dev/null)}"
if [ -z "$REPO_PATH" ]; then
    echo "Usage: $0 <repo-path>" >&2
    exit 1
fi

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

LAUNCHER_DIR="$HOME/.local/bin"
DESKTOP_DIR="$HOME/.local/share/applications"
ICON_HICOLOR_DIR="$HOME/.local/share/icons/hicolor"
ICON_SRC="$REPO_PATH/assets/leap-icon.png"
LAUNCHER_DEST="$LAUNCHER_DIR/leap-monitor"
DESKTOP_DEST="$DESKTOP_DIR/leap-monitor.desktop"

mkdir -p "$LAUNCHER_DIR" "$DESKTOP_DIR"

# Write launcher script with REPO_PATH baked in.
echo "→ Writing launcher script..."
{
    printf '#!/bin/bash\n'
    printf '# Generated by Leap — do not edit manually.\n'
    printf "# Re-run 'make install-monitor' to regenerate.\n"
    printf 'unset PYTHONHOME VIRTUAL_ENV\n'
    printf 'PROJECT_DIR="%s"\n' "$REPO_PATH"
    printf 'VENV_PATH_FILE="$PROJECT_DIR/.storage/venv-path"\n'
    printf 'if [ ! -f "$VENV_PATH_FILE" ]; then\n'
    printf "    echo \"Leap Monitor: venv not found. Run 'make install' in \$PROJECT_DIR\" >&2\n"
    printf '    exit 1\n'
    printf 'fi\n'
    printf 'VENV_BASE=$(cat "$VENV_PATH_FILE")\n'
    printf 'PYTHON_CMD="$VENV_BASE/bin/python3"\n'
    printf 'if [ ! -x "$PYTHON_CMD" ]; then\n'
    printf "    echo \"Leap Monitor: Python not found. Run 'make install' in \$PROJECT_DIR\" >&2\n"
    printf '    exit 1\n'
    printf 'fi\n'
    printf 'PYTHONPATH="%s/src${PYTHONPATH:+:$PYTHONPATH}" exec "$PYTHON_CMD" "%s/src/scripts/leap-monitor.py"\n' \
        "$REPO_PATH" "$REPO_PATH"
} > "$LAUNCHER_DEST"
chmod +x "$LAUNCHER_DEST"
printf "${GREEN}  ✓ Launcher: %s${NC}\n" "$LAUNCHER_DEST"

# Install icon into each hicolor size slot.
echo "→ Installing icon..."
if [ -f "$ICON_SRC" ]; then
    for size in 16 32 48 64 128 256 512; do
        SIZE_DIR="$ICON_HICOLOR_DIR/${size}x${size}/apps"
        mkdir -p "$SIZE_DIR"
        cp "$ICON_SRC" "$SIZE_DIR/leap-monitor.png"
    done
    ICON_REF="leap-monitor"
    printf "${GREEN}  ✓ Icon installed${NC}\n"
else
    ICON_REF="utilities-terminal"
    printf "${YELLOW}  ⚠ Icon not found at %s — using fallback icon${NC}\n" "$ICON_SRC"
fi

# Write .desktop file.
echo "→ Installing desktop entry..."
{
    printf '[Desktop Entry]\n'
    printf 'Name=Leap Monitor\n'
    printf 'Comment=AI CLI session manager monitor\n'
    printf 'Exec=%s\n' "$LAUNCHER_DEST"
    printf 'Icon=%s\n' "$ICON_REF"
    printf 'Type=Application\n'
    printf 'Categories=Development;Utility;\n'
    printf 'Terminal=false\n'
    printf 'StartupNotify=true\n'
} > "$DESKTOP_DEST"
printf "${GREEN}  ✓ Desktop entry: %s${NC}\n" "$DESKTOP_DEST"

# Refresh desktop and icon caches if tools are available.
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -f -t "$ICON_HICOLOR_DIR" 2>/dev/null || true
fi

echo ""
printf "${GREEN}✓ Leap Monitor installed!${NC}\n"
echo ""
echo "Launch Leap Monitor from:"
echo "  • App launcher: Search 'Leap Monitor'"
echo "  • Terminal: leap-monitor"
